### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by zinsbill** [nedbat/byterun#35]
Has anyone gotten this to run under Python 3? In Ubuntu, I tried 3.3 and 3.5 and 3.6... no luck, it always blew up at the same point. Actually, to be clear, Byterun sometimes worked to an extent, but the TESTS always blew up consistently, so that's what I mean by no luck. Has anyone gotten the tests to succeed?

**Comment by zinsbill** [comment]
...continued from above...     I am seeing this every time: 
-- stdout ----------
----------------------------------------------------------------------------------- Captured log call ------------------------------------------------------------------------------------
pyvm2.py                   241 ERROR    Caught exception during execution
Traceback (most recent call last):
  File "/home/willardz/devl/byterun/byterun/pyvm2.py", line 236, in dispatch
    why = bytecode_fn(*arguments)
  File "/home/willardz/devl/byterun/byterun/pyvm2.py", line 925, in byte_CALL_FUNCTION
    return self.call_function(arg, [], {})
  File "/home/willardz/devl/byterun/byterun/pyvm2.py", line 966, in call_function
    retval = func(*posargs, **namedargs)
TypeError: __build_class__: func must be a function
========================================================================== 41 failed, 58 passed in 1.81 seconds ==========================================================================

**Comment by zinsbill** [comment]
Closing this: I found the branch for Py3.
